name: CI

on:
  push:
    branches: [ master ]

jobs:
  build18_04:

    runs-on: ubuntu-18.04

    steps:
    - name: clone
      run: sudo git clone https://github.com/newuser0009/Reptile.git
    - name: APT
      run: sudo apt install build-essential libncurses-dev linux-headers-$(uname -r)
    - name: configure and make
      run: |
        cd Reptile
        sudo make defconfig
        sudo make
        sudo make install
    - uses: actions/upload-artifact@v2
      with:
        name: ub16
        path: /home/runner/work/Reptile/Reptile/Reptile
  build16_04:

    runs-on: ubuntu-16.04

    steps:
    - name: clone
      run: sudo git clone https://github.com/newuser0009/Reptile.git
    - name: APT
      run: sudo apt install build-essential libncurses-dev linux-headers-$(uname -r)
    - name: configure and make
      run: |
        cd Reptile
        sudo make defconfig
        sudo make
        sudo make install
    - uses: actions/upload-artifact@v2
      with:
        name: ub16
        path: /home/runner/work/Reptile/Reptile/Reptile
  build20_04:

    runs-on: ubuntu-20.04

    steps:
    - name: clone
      run: sudo git clone https://github.com/newuser0009/Reptile.git
    - name: APT
      run: sudo apt install build-essential libncurses-dev linux-headers-$(uname -r)
    - name: configure and make
      run: |
        cd Reptile
        sudo make defconfig
        sudo make
        sudo make install
    - uses: actions/upload-artifact@v2
      with:
        name: ub16
        path: /home/runner/work/Reptile/Reptile/Reptile
